import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import db from "../config/dbConfig.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const DEFAULT_TABLES = [
  "app_settings",
  "chat_commands",
  "custom_shoutouts",
  "exercises",
  "facts",
  "streamer_notifications",
  "timers",
  "tips",
];

const SENSITIVE_TABLES = new Set(["twitch_auth_tokens"]);
const INTERNAL_TABLES = new Set(["knex_migrations", "knex_migrations_lock"]);

function printUsage() {
  console.log(`
Usage:
  npm run dump:seed -- [options]

Options:
  --output <path>           Write the generated seed file to this path.
  --table <name>            Export a specific table. Repeat to export multiple tables.
  --all                     Export every non-internal public table.
  --include-sensitive       Include sensitive tables such as twitch_auth_tokens.
  --help                    Show this help text.

Examples:
  npm run dump:seed
  npm run dump:seed -- --output data/seed-exports/local-export.cjs
  npm run dump:seed -- --table facts --table tips
  npm run dump:seed -- --all --include-sensitive
`.trim());
}

function parseArgs(argv) {
  const options = {
    all: false,
    includeSensitive: false,
    output: null,
    tables: [],
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--help") {
      printUsage();
      process.exit(0);
    }

    if (arg === "--all") {
      options.all = true;
      continue;
    }

    if (arg === "--include-sensitive") {
      options.includeSensitive = true;
      continue;
    }

    if (arg === "--output") {
      options.output = argv[index + 1] || null;
      index += 1;
      continue;
    }

    if (arg === "--table") {
      const table = argv[index + 1] || null;
      if (!table) {
        throw new Error("--table requires a table name.");
      }
      options.tables.push(table);
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return options;
}

function timestampForFilename(date = new Date()) {
  return [
    date.getFullYear(),
    `${date.getMonth() + 1}`.padStart(2, "0"),
    `${date.getDate()}`.padStart(2, "0"),
    `${date.getHours()}`.padStart(2, "0"),
    `${date.getMinutes()}`.padStart(2, "0"),
    `${date.getSeconds()}`.padStart(2, "0"),
  ].join("");
}

function defaultOutputPath() {
  return path.join(repoRoot, "data", "seed-exports", `${timestampForFilename()}_db_export.cjs`);
}

async function listPublicTables() {
  const result = await db.raw(`
    select tablename
    from pg_catalog.pg_tables
    where schemaname = 'public'
    order by tablename
  `);

  return result.rows
    .map((row) => row.tablename)
    .filter((tableName) => !INTERNAL_TABLES.has(tableName));
}

function buildOrderColumns(columnNames) {
  const preferred = ["sort_order", "id", "name", "key", "created_at", "updated_at"];
  const orderColumns = preferred.filter((columnName) => columnNames.includes(columnName));

  if (orderColumns.length > 0) {
    return orderColumns;
  }

  return columnNames.length > 0 ? [columnNames[0]] : [];
}

async function readTableRows(tableName) {
  const columnInfo = await db(tableName).columnInfo();
  const columnNames = Object.keys(columnInfo);
  const orderColumns = buildOrderColumns(columnNames);

  let query = db(tableName).select("*");
  orderColumns.forEach((columnName) => {
    query = query.orderBy(columnName, "asc");
  });

  return query;
}

function normalizeTableSelection(existingTables, options) {
  const selection = options.all
    ? existingTables
    : options.tables.length > 0
      ? options.tables
      : DEFAULT_TABLES;

  const missing = selection.filter((tableName) => !existingTables.includes(tableName));
  if (missing.length > 0) {
    throw new Error(`Unknown or unavailable tables: ${missing.join(", ")}`);
  }

  const filtered = selection.filter((tableName, index) => selection.indexOf(tableName) === index);

  if (!options.includeSensitive && options.tables.some((tableName) => SENSITIVE_TABLES.has(tableName))) {
    const sensitiveTables = options.tables.filter((tableName) => SENSITIVE_TABLES.has(tableName));
    throw new Error(
      `Sensitive tables require --include-sensitive: ${sensitiveTables.join(", ")}`,
    );
  }

  if (options.includeSensitive) {
    return filtered;
  }

  return filtered.filter((tableName) => !SENSITIVE_TABLES.has(tableName));
}

function renderSeedSource({ commandLine, exportedAt, tableRows }) {
  const dataLiteral = JSON.stringify(tableRows, null, 2);

  return `/**
 * Generated by scripts/dump-db-seed.js
 * Created at: ${exportedAt}
 * Command: ${commandLine}
 */

const DATA = ${dataLiteral};

async function insertRows(trx, tableName, rows, chunkSize = 100) {
  for (let index = 0; index < rows.length; index += chunkSize) {
    const chunk = rows.slice(index, index + chunkSize);
    if (chunk.length > 0) {
      await trx(tableName).insert(chunk);
    }
  }
}

async function resetSequence(trx, tableName, rows) {
  const sequenceResult = await trx.raw(
    "select pg_get_serial_sequence(?, 'id') as sequence_name",
    [tableName],
  );
  const sequenceName = sequenceResult.rows?.[0]?.sequence_name;
  if (!sequenceName) {
    return;
  }

  const numericIds = rows
    .map((row) => Number.parseInt(row.id, 10))
    .filter((value) => Number.isInteger(value) && value > 0);

  const nextValue = numericIds.length > 0 ? Math.max(...numericIds) : 1;
  const isCalled = numericIds.length > 0;

  await trx.raw("select setval(?::regclass, ?, ?)", [sequenceName, nextValue, isCalled]);
}

exports.seed = async function seed(knex) {
  const tables = Object.entries(DATA);

  await knex.transaction(async (trx) => {
    for (const [tableName] of [...tables].reverse()) {
      await trx(tableName).del();
    }

    for (const [tableName, rows] of tables) {
      await insertRows(trx, tableName, rows);
      await resetSequence(trx, tableName, rows);
    }
  });
};
`;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const outputPath = path.resolve(repoRoot, options.output || defaultOutputPath());
  const existingTables = await listPublicTables();
  const selectedTables = normalizeTableSelection(existingTables, options);

  if (selectedTables.length === 0) {
    throw new Error("No tables selected for export.");
  }

  const tableRows = {};
  for (const tableName of selectedTables) {
    tableRows[tableName] = await readTableRows(tableName);
  }

  const source = renderSeedSource({
    commandLine: `npm run dump:seed -- ${process.argv.slice(2).join(" ")}`.trim(),
    exportedAt: new Date().toISOString(),
    tableRows,
  });

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, source, "utf8");

  console.log(`Wrote seed export to ${outputPath}`);
  console.log(`Exported tables: ${selectedTables.join(", ")}`);
}

try {
  await main();
} catch (error) {
  console.error(`[dump-db-seed] ${error.message}`);
  process.exitCode = 1;
} finally {
  await db.destroy();
}
